#!/bin/bash

# File to check
CONFIG_FILE="game/config.rpy"
prodia_line='prodia_api_key_demo = "PRODIA_DEMO_KEY"'
groq_line='groq_api_key_demo = "LLM_DEMO_KEY"'

if git diff --cached --name-only | grep -q "$CONFIG_FILE"; then
    if ! git show :$CONFIG_FILE | grep -q "$prodia_line"; then
        echo "Error: The line defining the prodia_api_key_demo should contain 'prodia_api_key_demo = \"PRODIA_DEMO_KEY\"'"
        echo "You can automatically undo the key switch using make config_undo"
        exit 1
    fi
    if ! git show :$CONFIG_FILE | grep -q "$groq_line"; then
        echo "Error: The line defining the groq_api_key_demo should contain 'groq_api_key_demo = \"LLM_DEMO_KEY\"'"
        echo "You can automatically undo the key switch using make config_undo"
        exit 1
    fi
fi

exit 0

